UserAuthProject/Controllers/ControlPanelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using UserAuthProject.Repositories.Interfaces;
using UserAuthProject.Services.Interfaces;

namespace UserAuthProject.Controllers
{
    [Route("api/[controller]")]
    [Authorize]
    public class ControlPanelController : AuthorizedController
    {
        public IUserRepository UserRepository { get; set; }

        public ControlPanelController(IAuthenticationService authenticationService,
            IHttpContextAccessor httpContextAccessor, IUserRepository userRepository) : base(authenticationService,
            httpContextAccessor)
        {
            this.UserRepository = userRepository;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var userId = User.FindFirstValue(ClaimTypes.Name);
            var user = UserRepository.GetUserById(Guid.Parse(userId));

            return View(user.Result);
        }
    }
}

UserAuthProject/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using UserAuthProject.Repositories.Interfaces;

namespace UserAuthProject.Controllers
{
    public class ProductsController : Controller
    {
        public IProductsRepository ProductsRepository { get; set; }

        public ProductsController(IProductsRepository productsRepository)
        {
            ProductsRepository = productsRepository;
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View(ProductsRepository.GetProducts().Result);
        }
    }
}

UserAuthProject/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using UserAuthProject.Models.DbContexts;
using UserAuthProject.Models.User;
using UserAuthProject.Repositories.Interfaces;
using UserAuthProject.Services.Interfaces;

namespace UserAuthProject.Controllers
{
    [Route("api/[controller]")]
    [Authorize]
    public class UsersController : AuthorizedController
    {
        private GlobalDbContext db { get; set; }
        public IUserRepository UserRepository { get; set; }

        public UsersController(GlobalDbContext userDbContext, IUserRepository userRepository,
            IHttpContextAccessor httpContextAccessor, IAuthenticationService authenticationService) : base(
            authenticationService, httpContextAccessor)
        {
            this.db = userDbContext;
            this.UserRepository = userRepository;
        }

        // GET: Users
        [HttpGet]
        public async Task<ActionResult> Index()
        {
            if (string.IsNullOrEmpty(User.FindFirstValue(ClaimTypes.Name)))
            {
                return RedirectToAction("Index", "Login");
            }

            return View(await db.Users.ToListAsync());
        }

        // GET: Users/Details/5
        [Route("details/{id}")]
        public async Task<ActionResult> Details(string id)
        {
            if (string.IsNullOrEmpty(User.FindFirstValue(ClaimTypes.Name)))
            {
                return RedirectToAction("Index", "Login");
            }

            if (id == null)
            {
                return BadRequest();
            }

            User user = await UserRepository.GetUserById(Guid.Parse(id));
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Users/Edit/5
        [Route("edit/{id}")]
        public async Task<ActionResult> Edit(string id)
        {
            if (string.IsNullOrEmpty(User.FindFirstValue(ClaimTypes.Name)))
            {
                return RedirectToAction("Index", "Login");
            }

            if (id == null)
            {
                return BadRequest();
            }

            User user = await UserRepository.GetUserById(Guid.Parse(id));
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(include: "Username,Email,RegistrationDate")]
            User user)
        {
            if (string.IsNullOrEmpty(User.FindFirstValue(ClaimTypes.Name)))
            {
                return RedirectToAction("Index", "Login");
            }

            if (ModelState.IsValid)
            {
                db.Entry(user).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(user);
        }

        // GET: Users/Delete/5
        [Route("delete/{id}")]
        public async Task<ActionResult> Delete(string id)
        {
            if (string.IsNullOrEmpty(User.FindFirstValue(ClaimTypes.Name)))
            {
                return RedirectToAction("Index", "Login");
            }

            if (id == null)
            {
                return BadRequest();
            }

            User user = await UserRepository.GetUserById(Guid.Parse(id));
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete/{id}")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            if (string.IsNullOrEmpty(User.FindFirstValue(ClaimTypes.Name)))
            {
                return RedirectToAction("Index", "Login");
            }

            User user = await UserRepository.GetUserById(Guid.Parse(id));
            db.Users.Remove(user);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }

            base.Dispose(disposing);
        }
    }
}

UserAuthProject/Views/Shared/_Layout.cshtml
@using UserAuthProject.Services.Interfaces
@using Microsoft.AspNetCore.Http
@using System.Security.Claims
@using UserAuthProject.Controllers
@inject IHttpContextAccessor HttpContextAccessor
@inject IAuthenticationService AuthenticationService

@{
    HttpContextAccessor.HttpContext.Request.Headers["AuthToken"] =
        IAuthenticationService.ReadCookie(HttpContextAccessor, LoginController.SessionKeyProperty);
    Console.WriteLine();
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - UserAuthProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body style="background-color: #333333; color: white">
<header>
    <nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">UserAuthProject</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse justify-content-between d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav ml-auto">
                    @if (!string.IsNullOrEmpty(User.FindFirstValue(ClaimTypes.Name)))
                    {
                        <li class="nav-item my-2 my-lg-0">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Logout">Logout</a>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Register" asp-action="Index">Register</a>
                        </li>
                    }
                </ul>
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                    </li>
                    @if (!string.IsNullOrEmpty(User.FindFirstValue(ClaimTypes.Name)))
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ControlPanel" asp-action="Index">Control Panel</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users Manager</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2020 - UserAuthProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@RenderSection("Scripts", required: false)
</body>
</html>